spring.datasource.url=jdbc:postgresql://localhost:5432/projectmanager
spring.datasource.username=admin
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
pm.app.jwtSecret=SuperSecretKeyForDevOnly12345678901234567890123456789012
ai.service.url=http://localhost:8000
